package what.a.pity.phone.call.paperthree.a.app

import android.app.Activity
import what.a.pity.phone.call.paperthree.R

class PaperThreeVariable {

    companion object {
        var isAppForeground = false
        var activityList = mutableListOf<Activity>()
        var jaddaauwdList = 0
        var isBackGround = false
        var isAppBackFor = false
        var exitAppTime = 0L
        var isToRequestPer = false



        var imageListBeautiful = mutableListOf(
            R.drawable.bt1,
            R.drawable.bt2,
            R.drawable.bt3,
            R.drawable.bt4,
            R.drawable.bt5,
            R.drawable.bt6,
            R.drawable.bt7,
            R.drawable.bt8,
            R.drawable.bt9,
            R.drawable.bt10,
            R.drawable.bt12,
            R.drawable.bt13,
            R.drawable.bt14,
            R.drawable.bt15,
            R.drawable.bt16,
            R.drawable.bt17,
            R.drawable.bt19,
            R.drawable.bt21,
            R.drawable.bt22,
            R.drawable.bt23,
            R.drawable.bt25,
            R.drawable.bt29,
            R.drawable.bt30,
            R.drawable.bt31,
            R.drawable.bt32,
            R.drawable.bt34,
            R.drawable.bt35,
        )
        var imageListNature = mutableListOf(
            R.drawable.nt1,
            R.drawable.nt2,
            R.drawable.nt3,
            R.drawable.nt4,
            R.drawable.nt5,
            R.drawable.nt6,
            R.drawable.nt7,
            R.drawable.nt8,
            R.drawable.nt9,
            R.drawable.nt10,
            R.drawable.nt11,
            R.drawable.nt12,
            R.drawable.nt13,
            R.drawable.nt14,
            R.drawable.nt15,
            R.drawable.nt16,
            R.drawable.nt17,
            R.drawable.nt18,
            R.drawable.nt19,
            R.drawable.nt23,
            R.drawable.nt24,
            R.drawable.nt25,
            R.drawable.nt27,
            R.drawable.nt29,
            R.drawable.nt30,
            R.drawable.nt31,
            R.drawable.nt33,
            R.drawable.nt34,

        )
        var imageListCity = mutableListOf(
            R.drawable.ct1,
            R.drawable.ct2,
            R.drawable.ct3,
            R.drawable.ct4,
            R.drawable.ct5,
            R.drawable.ct6,
            R.drawable.ct7,
            R.drawable.ct8,
            R.drawable.ct9,
            R.drawable.ct10,
            R.drawable.ct12,
            R.drawable.ct13,
            R.drawable.ct14,
            R.drawable.ct15,
            R.drawable.ct16,
            R.drawable.ct20,
            R.drawable.ct21,
            R.drawable.ct22,
            R.drawable.ct23,
            R.drawable.ct24,
            R.drawable.ct25,
            R.drawable.ct26,
            R.drawable.ct27,
            R.drawable.ct28,
            R.drawable.ct29,
            R.drawable.ct30,
        )
        var imageListArt = mutableListOf(
            R.drawable.at1,
            R.drawable.at2,
            R.drawable.at3,
            R.drawable.at4,
            R.drawable.at5,
            R.drawable.at6,
            R.drawable.at7,
            R.drawable.at8,
            R.drawable.at9,
            R.drawable.at10,
            R.drawable.at14,
            R.drawable.at16,
            R.drawable.at17,
            R.drawable.at18,
            R.drawable.at19,
            R.drawable.at20,
            R.drawable.at21,
            R.drawable.at22,
            R.drawable.at23,
            R.drawable.at24,
            R.drawable.at26,
            R.drawable.at27,
            R.drawable.at29,
            R.drawable.at30,
            R.drawable.at31,
            R.drawable.at33,
            R.drawable.at34,
            R.drawable.at35,
        )
        var imageListAnime = mutableListOf(
            R.drawable.am1,
            R.drawable.am2,
            R.drawable.am3,
            R.drawable.am4,
            R.drawable.am5,
            R.drawable.am6,
            R.drawable.am7,
            R.drawable.am8,
            R.drawable.am9,
            R.drawable.am10,
            R.drawable.am12,
            R.drawable.am13,
            R.drawable.am14,
            R.drawable.am15,
            R.drawable.am16,
            R.drawable.am17,
            R.drawable.am18,
            R.drawable.am19,
            R.drawable.am20,
            R.drawable.am21,
            R.drawable.am22,
            R.drawable.am24,
            R.drawable.am27,
            R.drawable.am29,
            R.drawable.am31,
            R.drawable.am32,
            R.drawable.am36,
            R.drawable.am37,
            R.drawable.am38,
            R.drawable.am39,
            R.drawable.am40,
            R.drawable.am42,
        )
        var imageListCool = mutableListOf(
            R.drawable.cl1,
            R.drawable.cl2,
            R.drawable.cl3,
            R.drawable.cl4,
            R.drawable.cl5,
            R.drawable.cl6,
            R.drawable.cl7,
            R.drawable.cl8,
            R.drawable.cl9,
            R.drawable.cl10,
            R.drawable.cl12,
            R.drawable.cl13,
            R.drawable.cl14,
            R.drawable.cl15,
            R.drawable.cl17,
            R.drawable.cl18,
            R.drawable.cl19,
            R.drawable.cl20,
            R.drawable.cl21,
            R.drawable.cl22,
            R.drawable.cl23,
            R.drawable.cl24,
            R.drawable.cl25,
            R.drawable.cl26,
            R.drawable.cl31,
            R.drawable.cl32,
            R.drawable.cl33,
            R.drawable.cl34,
        )

        var imgLightAdList = mutableListOf(
            R.drawable.ic_top_fire,
            R.drawable.ic_ad_2,
            R.drawable.ic_ad_3,
            R.drawable.ic_ad_4,
            R.drawable.ic_ad_5,
            R.drawable.ic_ad_6,
            R.drawable.ic_ad_7
        )

        var imgLightPopList = mutableListOf(
            R.drawable.ic_57,
            R.drawable.ic_58,
            R.drawable.ic_59,
            R.drawable.ic_60,
            R.drawable.ic_61,
            R.drawable.ic_62,
            R.drawable.ic_63,
            R.drawable.ic_64,
            R.drawable.ic_65,
            R.drawable.ic_66,
            R.drawable.ic_67,
            R.drawable.ic_68,
            R.drawable.ic_69,
            R.drawable.ic_70,
            R.drawable.ic_71,
            R.drawable.ic_72,
            R.drawable.ic_73,
            R.drawable.ic_74,
            R.drawable.ic_75,
            R.drawable.ic_76,
        )

        var imageLightWallList = mutableListOf(
            0,
            R.drawable.nt1,
            R.drawable.nt3,
            R.drawable.cl1,
            R.drawable.cl3,

            R.drawable.bt1,
            R.drawable.bt3,

            R.drawable.am1,
            R.drawable.am3,

            R.drawable.ct1,
            R.drawable.ct3,

            R.drawable.at1,
            R.drawable.at3,
        )

    }
}