package what.a.pity.phone.call.paperthree.a.app

import android.app.Activity
import what.a.pity.phone.call.paperthree.R

class PaperThreeVariable {

    companion object {
        var isAppForeground = false
        var activityList = mutableListOf<Activity>()
        var jaddaauwdList = 0
        var isBackGround = false
        var isAppBackFor = false
        var exitAppTime = 0L
        var isToRequestPer = false



        var imageListBeautiful = mutableListOf(
            R.drawable.bt1,
            R.drawable.bt2,
            R.drawable.bt3,
            R.drawable.bt4,
            R.drawable.bt5,
            R.drawable.bt6,
            R.drawable.bt7,
            R.drawable.bt8,
            R.drawable.bt9,
            R.drawable.bt10,
            R.drawable.bt12,
            R.drawable.bt13,
            R.drawable.bt14,
            R.drawable.bt15,
            R.drawable.bt16,
            R.drawable.bt17,
            R.drawable.bt18,
            R.drawable.bt19,
            R.drawable.bt20,
            R.drawable.bt21,
            R.drawable.bt22,
            R.drawable.bt23,
            R.drawable.bt24,
            R.drawable.bt25,
            R.drawable.bt26,
            R.drawable.bt27,
            R.drawable.bt28,
            R.drawable.bt29,
            R.drawable.bt30,
            R.drawable.bt31,
            R.drawable.bt32,
            R.drawable.bt33,
            R.drawable.bt34,
            R.drawable.bt35,
            R.drawable.bt36,
            R.drawable.bt37,
            R.drawable.bt38,
            R.drawable.bt39,
            R.drawable.bt40,
            R.drawable.bt41,
            R.drawable.bt42,
            R.drawable.bt43,
            R.drawable.bt44,
            R.drawable.bt45,
            R.drawable.bt46,
            R.drawable.bt47,
            R.drawable.bt48,
            R.drawable.bt49,
            R.drawable.bt50,
        )
        var imageListNature = mutableListOf(
            R.drawable.nt1,
            R.drawable.nt2,
            R.drawable.nt3,
            R.drawable.nt4,
            R.drawable.nt5,
            R.drawable.nt6,
            R.drawable.nt7,
            R.drawable.nt8,
            R.drawable.nt9,
            R.drawable.nt10,

            R.drawable.nt11,
            R.drawable.nt12,
            R.drawable.nt13,
            R.drawable.nt14,
            R.drawable.nt15,
            R.drawable.nt16,
            R.drawable.nt17,
            R.drawable.nt18,
            R.drawable.nt19,
            R.drawable.nt20,

            R.drawable.nt21,
            R.drawable.nt22,
            R.drawable.nt23,
            R.drawable.nt24,
            R.drawable.nt25,
            R.drawable.nt26,
            R.drawable.nt27,
            R.drawable.nt28,
            R.drawable.nt29,
            R.drawable.nt30,

            R.drawable.nt31,
            R.drawable.nt32,
            R.drawable.nt33,
            R.drawable.nt34,
            R.drawable.nt35,
            R.drawable.nt36,
            R.drawable.nt37,
            R.drawable.nt38,
            R.drawable.nt39,
            R.drawable.nt40,

            R.drawable.nt41,
            R.drawable.nt42,
            R.drawable.nt43,
            R.drawable.nt44,
            R.drawable.nt45,
            R.drawable.nt46,
            R.drawable.nt47,

        )
        var imageListCity = mutableListOf(
            R.drawable.ct1,
            R.drawable.ct2,
            R.drawable.ct3,
            R.drawable.ct4,
            R.drawable.ct5,
            R.drawable.ct6,
            R.drawable.ct7,
            R.drawable.ct8,
            R.drawable.ct9,
            R.drawable.ct10,
            R.drawable.ct12,
            R.drawable.ct13,
            R.drawable.ct14,
            R.drawable.ct15,
            R.drawable.ct16,
            R.drawable.ct17,
            R.drawable.ct18,
            R.drawable.ct19,
            R.drawable.ct20,
            R.drawable.ct21,
            R.drawable.ct22,
            R.drawable.ct23,
            R.drawable.ct24,
            R.drawable.ct25,
            R.drawable.ct26,
            R.drawable.ct27,
            R.drawable.ct28,
            R.drawable.ct29,
            R.drawable.ct30,
            R.drawable.ct31,
            R.drawable.ct32,
            R.drawable.ct33,
            R.drawable.ct34,
            R.drawable.ct35,
            R.drawable.ct36,
            R.drawable.ct37,
            R.drawable.ct38,
            R.drawable.ct39,
            R.drawable.ct40,
            R.drawable.ct41,
            R.drawable.ct42,
            R.drawable.ct43,
            R.drawable.ct44,
            R.drawable.ct45,
            R.drawable.ct46,
        )
        var imageListArt = mutableListOf(
            R.drawable.at1,
            R.drawable.at2,
            R.drawable.at3,
            R.drawable.at4,
            R.drawable.at5,
            R.drawable.at6,
            R.drawable.at7,
            R.drawable.at8,
            R.drawable.at9,
            R.drawable.at10,
            R.drawable.at14,
            R.drawable.at16,
            R.drawable.at17,
            R.drawable.at18,
            R.drawable.at19,
            R.drawable.at20,
            R.drawable.at21,
            R.drawable.at22,
            R.drawable.at23,
            R.drawable.at24,
            R.drawable.at25,
            R.drawable.at26,
            R.drawable.at27,
            R.drawable.at28,
            R.drawable.at29,
            R.drawable.at30,
            R.drawable.at31,
            R.drawable.at32,
            R.drawable.at33,
            R.drawable.at34,
            R.drawable.at35,
            R.drawable.at36,
            R.drawable.at37,
            R.drawable.at38,
            R.drawable.at39,
            R.drawable.at40,
            R.drawable.at41,
            R.drawable.at42,
            R.drawable.at43,
            R.drawable.at44,
            R.drawable.at45,
            R.drawable.at46,
            R.drawable.at47,
            R.drawable.at48,
        )
        var imageListAnime = mutableListOf(
            R.drawable.am1,
            R.drawable.am2,
            R.drawable.am3,
            R.drawable.am4,
            R.drawable.am5,
            R.drawable.am6,
            R.drawable.am7,
            R.drawable.am8,
            R.drawable.am9,
            R.drawable.am10,
            R.drawable.am12,
            R.drawable.am13,
            R.drawable.am14,
            R.drawable.am15,
            R.drawable.am16,
            R.drawable.am17,
            R.drawable.am18,
            R.drawable.am19,
            R.drawable.am20,
            R.drawable.am21,
            R.drawable.am22,
            R.drawable.am23,
            R.drawable.am24,
            R.drawable.am25,
            R.drawable.am26,
            R.drawable.am27,
            R.drawable.am28,
            R.drawable.am29,
            R.drawable.am30,
            R.drawable.am31,
            R.drawable.am32,
            R.drawable.am33,
            R.drawable.am34,
            R.drawable.am35,
            R.drawable.am36,
            R.drawable.am37,
            R.drawable.am38,
            R.drawable.am39,
            R.drawable.am40,
            R.drawable.am41,
            R.drawable.am42,
            R.drawable.am43,
            R.drawable.am44,
            R.drawable.am45,
            R.drawable.am46,
            R.drawable.am47,
            R.drawable.am48,
            R.drawable.am49,
            R.drawable.am50,
            R.drawable.am61,
            R.drawable.am62,
            R.drawable.am63,
        )
        var imageListCool = mutableListOf(
            R.drawable.cl1,
            R.drawable.cl2,
            R.drawable.cl3,
            R.drawable.cl4,
            R.drawable.cl5,
            R.drawable.cl6,
            R.drawable.cl7,
            R.drawable.cl8,
            R.drawable.cl9,
            R.drawable.cl10,
            R.drawable.cl12,
            R.drawable.cl13,
            R.drawable.cl14,
            R.drawable.cl15,
            R.drawable.cl17,
            R.drawable.cl18,
            R.drawable.cl19,
            R.drawable.cl20,
            R.drawable.cl21,
            R.drawable.cl22,
            R.drawable.cl23,
            R.drawable.cl24,
            R.drawable.cl25,
            R.drawable.cl26,
            R.drawable.cl27,
            R.drawable.cl28,
            R.drawable.cl29,
            R.drawable.cl30,
            R.drawable.cl31,
            R.drawable.cl32,
            R.drawable.cl33,
            R.drawable.cl34,
            R.drawable.cl35,
            R.drawable.cl36,
            R.drawable.cl37,
            R.drawable.cl38,
            R.drawable.cl39,
            R.drawable.cl40,
            R.drawable.cl41,
            R.drawable.cl42,
            R.drawable.cl43,
            R.drawable.cl44,
            R.drawable.cl45,
            R.drawable.cl46,
            R.drawable.cl47,
            R.drawable.cl48,
            R.drawable.cl49,
            R.drawable.cl50,
            R.drawable.cl51,
            R.drawable.cl52,
            R.drawable.cl53,
            R.drawable.cl54,
        )

        var imgLightAdList = mutableListOf(
            R.drawable.ic_top_fire,
            R.drawable.ic_ad_2,
            R.drawable.ic_ad_3,
            R.drawable.ic_ad_4,
            R.drawable.ic_ad_5,
            R.drawable.ic_ad_6,
            R.drawable.ic_ad_7
        )

        var imgLightPopList = mutableListOf(
            R.drawable.ic_57,
            R.drawable.ic_58,
            R.drawable.ic_59,
            R.drawable.ic_60,
            R.drawable.ic_61,
            R.drawable.ic_62,
            R.drawable.ic_63,
            R.drawable.ic_64,
            R.drawable.ic_65,
            R.drawable.ic_66,
            R.drawable.ic_67,
            R.drawable.ic_68,
            R.drawable.ic_69,
            R.drawable.ic_70,
            R.drawable.ic_71,
            R.drawable.ic_72,
            R.drawable.ic_73,
            R.drawable.ic_74,
            R.drawable.ic_75,
            R.drawable.ic_76,
        )

        var imageLightWallList = mutableListOf(
            0,
            R.drawable.nt1,
            R.drawable.nt3,
            R.drawable.cl1,
            R.drawable.cl3,

            R.drawable.bt1,
            R.drawable.bt3,

            R.drawable.am1,
            R.drawable.am3,

            R.drawable.ct1,
            R.drawable.ct3,

            R.drawable.at1,
            R.drawable.at3,
        )

    }
}